using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleConsoleWindow : FancyWindow,
    IComputerWindow<ShuttleNavigatorRadarBoundInterfaceState>
{
    public ShuttleConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        Tabs.SetTabTitle(0, Loc.GetString("shuttle-console-local-tab"));
        Tabs.SetTabTitle(1, Loc.GetString("shuttle-console-overmap-tab"));
    }

    public RadarTab ControlRadarTab => RadarTab;
    public OvermapTab ControlOvermapTab => OvermapTab;

    public void UpdateState(ShuttleNavigatorRadarBoundInterfaceState state)
    {
        if (state.RadarConsoleState is { } radarState)
            ControlRadarTab.UpdateState(radarState);

        if (state.NavigatorState is { } navigatorState)
            OvermapTab.UpdateState(navigatorState);
    }
}
